name: Build and Deploy
on:
  push:
    branches:
      - main  # replace with your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0  # replace with your Node.js version

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
